#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but for the 9th iteration it displays Best School and then Hi

index=0

while [ $index -lt 10 ]
do
  if [ $index -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( index++ ))
done

