#!/usr/bin/env bash
#This script display "Best School" and displays:
#  "bad luck" for the 4th iteration
#  "good luck" for the 8th iteration
#  "Best School" for all other iterations

COUNT=1
while [ $COUNT -lt 11 ]
do
	if [ $COUNT -eq 4 ]
	then
		echo "bad luck"
	elif [ $COUNT -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	COUNT=$(( COUNT + 1 ))
done
