#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

HOUR=0
MINUTE=1
while [ $HOUR -lt 13 ]
do
	echo "Hour: $HOUR"
	while [ $MINUTE -lt 60 ]
	do
		echo $MINUTE
		MINUTE=$(( MINUTE + 1 ))
	done
	HOUR=$(( HOUR + 1 ))
	MINUTE=1
done
